#!/usr/bin/env bash
# Nginx installation script

# Requirements:

# Install nginx on your web server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Holberton School
apt-get update
apt-get install nginx -y
echo "Holberton School" > /usr/share/nginx/html/index.html
service nginx restart
