#!/usr/bin/env bash
# Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs and killed the nginx process after
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
pkill -SIGHUP nginx
