#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times but for the 9 iteration display Hi

i=1
while [ $i -le 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "Hi"
	else
		echo "Holberton School"
	fi
	((i++))
done
