#!/usr/bin/env bash
# Run master and worker process of nginx as a non-root user 'nginx'
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sed -i -e 's/#user www-data/user nginx/g' /etc/nginx/nginx.conf
sed -i -e "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx /etc/init.d/nginx start
